#!/bin/bash

# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright (c) 2010 ForgeRock AS. All Rights Reserved
# Copyright 2011 Cybernetica AS.
#
# The contents of this file are subject to the terms
# of the Common Development and Distribution License
# (the License). You may not use this file except in
# compliance with the License.
#
# You can obtain a copy of the License at
# http://forgerock.org/license/CDDLv1.0.html
# See the License for the specific language governing
# permission and limitations under the License.
#
# When distributing Covered Code, include this CDDL
# Header Notice in each file and include the License file
# at http://forgerock.org/license/CDDLv1.0.html
# If applicable, add the following below the CDDL Header,
# with the fields enclosed by brackets [] replaced by
# your own identifying information:
# "Portions Copyrighted [year] [name of copyright owner]"
#
#

ADMIN_TOOLS_DIR=~/bin

SERVICE_NAME=iPlanetAMAuthOAuthService
MODULE_CLASS="org.forgerock.openam.authentication.modules.oauth2"

ADMIN_USER=amAdmin
ADMIN_PASS_FILE=~/.pass

cd $ADMIN_TOOLS_DIR
./ssoadm unregister-auth-module -a $MODULE_CLASS -u $ADMIN_USER -f $ADMIN_PASS_FILE
./ssoadm delete-svc -s $SERVICE_NAME -u $ADMIN_USER -f $ADMIN_PASS_FILE
