#!/bin/bash

# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright (c) 2010 ForgeRock AS. All Rights Reserved
#
# The contents of this file are subject to the terms
# of the Common Development and Distribution License
# (the License). You may not use this file except in
# compliance with the License.
#
# You can obtain a copy of the License at
# http://forgerock.org/license/CDDLv1.0.html
# See the License for the specific language governing
# permission and limitations under the License.
#
# When distributing Covered Code, include this CDDL
# Header Notice in each file and include the License file
# at http://forgerock.org/license/CDDLv1.0.html
# If applicable, add the following below the CDDL Header,
# with the fields enclosed by brackets [] replaced by
# your own identifying information:
# "Portions Copyrighted [year] [name of copyright owner]"
#
# Copyright 2011 Cybernetica AS.
#

# change this to appropriate application directory
APP_DIR=~/apache-tomcat-6.0.30/webapps/opensso

CLASSES=$APP_DIR/WEB-INF/classes
CONFIGS=$APP_DIR/config/auth/default
SRC_DIR=`pwd`

MODULE_NAME=OAuth

SVC_NAME=amAuth$MODULE_NAME
SVC_PROP_FILE=$SVC_NAME.properties
SVC_DESC_FILE=$SVC_NAME.xml

cp $SRC_DIR/target/*.jar $APP_DIR/WEB-INF/lib/
cp $SRC_DIR/src/conf/$SVC_PROP_FILE $CLASSES/
cp $SRC_DIR/src/conf/$SVC_DESC_FILE $CLASSES/
cp $SRC_DIR/src/conf/$MODULE_NAME.xml $CONFIGS/

SVC_NAME=amUser
SVC_PROP_FILE=$SVC_NAME.properties
SVC_DESC_FILE=$SVC_NAME.xml

cp $SRC_DIR/src/conf/$SVC_PROP_FILE $CLASSES/
cp $SRC_DIR/src/conf/$SVC_DESC_FILE $CLASSES/

for file in `find src/ -name *.jsp`; do
  echo "Copying $file to $CONFIGS";
  cp $file $CONFIGS/;
done;

# If module logging does not work, go to global configuration,
# servers and sites tab, click on your site and change logging
# level there to a different value, then change it back to the
# original value.

